### ISSUE TITLE
Revisión del README

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twIE_2021-proyecto_asfj#1]
Hola,

Aún no habéis cumplimentado la plantilla con vuestra propuesta.

**Comment by juliamgy** [comment]
Buenos días,
Ya he rellenado la plantilla

**Comment by oscarperpinan** [comment]
He revisado el README:

- La propuesta de trabajo es adecuada. Adelante.
- Eliminad los corchetes.
- En la lista de participantes usad el formato lista de Markdown.
- Podéis enlazar cada participante a su página web de GitHub.

**Comment by juliamgy** [comment]
Ya he perfeccionado el README
