### ISSUE TITLE
Uso de system

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twIE_2021-proyecto_asfj#10]
La función system pertenece a la librería stdlib.h, que no habéis declarado al principio con una directiva include. Por otra parte, debéis evitar su uso porque hace llamadas a comandos del sistema operativo y, por tanto, no es portable: lo que funciona en windows no funciona en linux o mac, y viceversa.

https://github.com/aigora/twIE_2021-proyecto_asfj/blob/7d02a7f833e68f4ea7db9f80dde2f66f2fbf599d/Proyecto%20ASFJ.c#L33

**Comment by Azuazuazu** [comment]
¿Existe otra función o forma de limpiar la pantalla que si podamos usar?

**Comment by oscarperpinan** [comment]
Una solución sencilla es emplear los _ANSI escape codes_. Hablé de ellos en [una respuesta en el canal de tutorías](https://teams.microsoft.com/l/message/19:98e916bb4a3a46a6ac3150257541425d@thread.tacv2/1615334973963?tenantId=6afea85d-c323-4270-b69d-a4fb3927c254&groupId=3477ddd6-cbb2-4bb5-ad31-ecefaebf2091&parentMessageId=1615327042869&teamName=Inform%C3%A1tica%2056IE%20(2020-21)&channelName=Tutor%C3%ADas&createdTime=1615334973963). Probad con:
`printf("\033[2J");`

**Comment by Azuazuazu** [comment]
Lo probé pero sólo imprime en pantalla "←[2J" y continúa el programa tal cual.

**Comment by oscarperpinan** [comment]
Ten en cuenta que en Windows debes instalar Windows Terminal: https://aka.ms/terminal

**Comment by Azuazuazu** [comment]
Ya hemos sustituido Fabio y yo todos los system("cls") por comandos ANSI.  ¿Funciona así en Linux también? 
He evitado además el uso de la librería windows.h.
¿Hay algún otro comando que de problemas?
