### ISSUE TITLE
Diagrama de flujo

### ISSUE THREAD

**Issue by orgynmobs** [aigora/twIE_2021-proyecto_asfj#2]
Debéis crear un fichero en formato [PDF](https://help.github.com/en/articles/rendering-pdf-documents), [GIF, JPEG o PNG](https://help.github.com/en/articles/rendering-and-diffing-images) (**no se admiten documentos Word o similar**) representando el [diagrama de flujo](https://es.wikipedia.org/wiki/Diagrama_de_flujo) previsto para vuestro programa. 
En el punto de inicio tenéis un [tutorial](https://github.com/aigora/punto_inicio/wiki/6.1-C%C3%B3mo-realizar-un-diagrama-de-flujo) para crear diagramas de flujo.
Este diagrama os servirá de guía para la implementación del trabajo. No obstante, ésta será la primera versión, por lo que según vayáis avanzando en el desarrollo del programa podréis y deberéis modificarlo.

**Comment by juliamgy** [comment]
Buenas tardes, he añadido un nuevo fichero en el cual he subido un archivo pdf que es el diagrama de flujo. No se si esa es la forma adecuada de "entregar" el diagrama de flujo. ¿Lo tengo que subir de otra forma o así está bien?

**Comment by oscarperpinan** [comment]
Así es como hay que hacerlo. Podéis cerrar esta tarea cuando lo deis por finalizado.

**Comment by juliamgy** [comment]
Perfecto! Gracias!
