### ISSUE TITLE
Definición de las estructuras

### ISSUE THREAD

**Issue by orgynmobs** [aigora/twIE_2021-proyecto_asfj#5]
Debéis implementar la definición de las principales estructuras (datos tipo `struct`) que se usan en el programa.
 Esta implementación puede tener cambios en la versión definitiva.

**Comment by Azuazuazu** [comment]
He definido dos estructuras para más adelante usarlas en el calendario. Una de ellas estará dentro de la otra.
Además con otra estructura di valores a la fecha en tiempo real.
