### ISSUE TITLE
Documentación en wiki

### ISSUE THREAD

**Issue by orgynmobs** [aigora/twIE_2021-proyecto_asfj#8]
Acompañando al código, hay que elaborar la documentación del proyecto. Esta documentación debe estar recogida en la wiki del repositorio.

En el punto de inicio tenéis las [instrucciones](https://github.com/aigora/punto_inicio/wiki/6.-C%C3%B3mo-presentar-el-trabajo) necesarias.

**Debéis cerrar esta issue cuando deis por finalizado el trabajo.**

**Comment by juliamgy** [comment]
Buenos días Óscar, tengo una duda sobre la organización de la wiki. 

La he estado redactando, haciendo varios apartados sobre los temas tratados en una misma pagina. He visto que algunos compañeros han hecho varias páginas y en cada una han explicado un apartado diferente.
¿Es indiferente como esté distribuida la información o recomiendas hacerlo usando varias páginas? 
Es para saber si debo cambiarla

Gracias!
